"""
AUTONOMOUS TEST 4: ODOO CRM SKILL
- Connect
- Dashboard Data (Leads)
- Add Lead (Dummy Data)
"""
import sys
import os
import logging
from datetime import datetime
sys.path.insert(0, os.path.abspath('.'))

from src.utils.config import Config
from skills.odoo_skill.skill import OdooSkill

# Configure Logging
logging.basicConfig(level=logging.INFO, format='%(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("OdooTest")

def test_odoo():
    print("\n🧪 TESTING ODOO CRM SKILL PROPERLY...")
    
    # 1. Initialize
    print("\n[1/3] Initializing Odoo Skill...")
    try:
        odoo_skill = OdooSkill()
        
        if odoo_skill.authenticate():
            print(f"   ✅ Connection Successful (UID: {odoo_skill.uid})")
        else:
            print("   ❌ Connection Failed (No UID)")
            return
            
    except Exception as e:
        print(f"   ❌ Initialization Error: {e}")
        return

    # 2. Creating Lead
    print("\n[2/3] Creating Dummy Lead...")
    try:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        lead_data = {
            'name': f"Autonomous Test Lead {timestamp}",
            'email': f"test_{timestamp}@example.com",
            'description': "Generated by autonomous testing suite."
        }
        
        result = odoo_skill.create_lead(**lead_data)
        
        if result.get('success'):
            print(f"   ✅ Lead Created Successfully (ID: {result.get('lead_id')})")
        else:
            print(f"   ❌ Lead Creation Failed: {result.get('error')}")
            
    except Exception as e:
        print(f"   ❌ Create Error: {e}")

    # 3. Getting Leads (Dashboard)
    print("\n[3/3] Fetching Dashboard Data (Leads)...")
    try:
        result = odoo_skill.get_leads(limit=5)
        
        if isinstance(result, list):
            leads = result
            print(f"   ✅ Fetched {len(leads)} leads")
            
            if leads:
                l = leads[0]
                print(f"   📊 Sample: [{l.get('id')}] {l.get('name')} (Status: {l.get('stage_id', 'Unknown')})")
        else:
            print(f"   ❌ Fetch Failed (Invalid Format): {result}")
            
    except Exception as e:
        print(f"   ❌ Fetch Error: {e}")

if __name__ == "__main__":
    test_odoo()
