import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.odoo_agent import OdooAgent

def test_odoo_agent():
    print("Testing Odoo Agent...")
    agent = OdooAgent()
    
    # Test status
    status = agent.get_status()
    print(f"Agent Status: {status}")
    
    if not status['enabled']:
        print("FAIL: Agent disabled (check .env)")
        return

    # Test Lead Creation (Mock Data)
    print("Testing Lead Creation...")
    result = agent.create_lead_from_email({
        "subject": "Test Lead from Script",
        "sender": "test@example.com",
        "body": "This is a test lead generated by the verification script."
    })
    print(f"Creation Result: {result}")
    
    if result.get("success"):
        print("PASS: Lead created successfully")
    else:
        print("FAIL: Lead creation failed")

if __name__ == "__main__":
    test_odoo_agent()
